#include <stdio.h>
#include <stdlib.h>
#include <signal.h>

#ifdef _WIN32
#include <winsock2.h>
#include <windows.h>
#pragma comment(lib, "ws2_32.lib")
#else
#include <unistd.h>
#endif

#include "connection_handler.h"
#include "logger.h"
#include "file_transfer.h"

int server_fd;

/**
 * @brief Signal handler for SIGINT.
 *
 * This function handles the SIGINT signal (typically generated by pressing Ctrl+C).
 * It logs a shutdown message, closes the server socket, and exits the program.
 *
 * @param signal The signal number.
 */
void handle_signal(int signal) {
    if (signal == SIGINT) {
        log_info("Shutting down server...");
#ifdef _WIN32
        closesocket(server_fd);
        WSACleanup();
#else
        close(server_fd);
#endif
        exit(0);
    }
}

/**
 * @brief Main function for the server application.
 *
 * This function initializes the server, sets up signal handling, and waits for clients to connect.
 *
 * @param argc The number of command-line arguments.
 * @param argv The array of command-line arguments.
 * @return 0 on success, 1 on failure.
 */
int main(int argc, char *argv[]) {
    const char *ip_address = argv[1];
    const char *file_name = argv[2];

    signal(SIGINT, handle_signal);
    
    initialize_directories();

    server_fd = initialize_server(ip_address);
    if (server_fd < 0) {
        log_error("Failed to initialize server");
        return 1;
    }

    log_info("Server is running. Waiting for clients...");

    accept_client(server_fd, file_name);

    return 0;
}